# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run isort
      uses: isort/isort-action@master
    - name: Run black
      uses: psf/black@stable
    - name: Run flake8 Lint
      run: |
        python -m pip install --upgrade flake8
        flake8 --version
        flake8 --ignore E266 E501 E731 W503 D107 --max-line-length 100 --max-complexity=10
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run pytest
        run: |
          pytest
